# simple axb Makefile to build a c and a assembler program

AXB_PROJECT=hello
AXB_PROGRAMS=hello
AXB_SRCS_C_hello=hello.c

AXB_TOP ?= $(PWD)/../..
AXB_BUILD_TOP ?= $(PWD)/..
include $(AXB_TOP)/axb.mk
