# simple axb Makefile to build a program with a single source file

AXB_TOP = $(PWD)/../..
include $(AXB_TOP)/axb_def.mk

AXB_PROJECT=hello
AXB_C_SRCS=hello.c

# the two lines are required to setup axb in your Makefile
include $(AXB_TOP)/axb_rules.mk
